### ISSUE TITLE
chapter6 cifar10-cnn

### ISSUE THREAD

**Issue by annzheng** [huxiaoman7/learningdl#2]
I got this problem when I ran cifar10-cnn.ipynb:
<ipython-input-12-870fd1d84079> in <module>()
      5 import tarfile
      6 import tensorflow as tf
----> 7 import CIFAR10.CIFAR_input as input
      8 FLAGS=tf.app.flags.FLAGS
      9 

ModuleNotFoundError: No module named 'CIFAR10'

<ipython-input-13-fcefae98e9ad> in <module>()
      4 import time
      5 import tensorflow as tf
----> 6 from CIFAR10 import model_build
      7 FLAGS=tf.app.flags.FLAGS
      8 

ModuleNotFoundError: No module named 'CIFAR10'

**Comment by huxiaoman7** [comment]
hi，你好，这个需要你从tensorflow的github里下载cifar10这个包，里面有很多模块，这样才能导入model_build模块
